on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Reload deno.lock
        run: |
          rm deno.lock
          deno install --reload
        shell: bash

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Refresh deno.lock"
          git push
        shell: bash
